# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  DarkRenderer_config = debug
endif
ifeq ($(config),release)
  DarkRenderer_config = release
endif
ifeq ($(config),fpga)
  DarkRenderer_config = fpga
endif

PROJECTS := DarkRenderer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DarkRenderer:
ifneq (,$(DarkRenderer_config))
	@echo "==== Building DarkRenderer ($(DarkRenderer_config)) ===="
	@${MAKE} --no-print-directory -C . -f DarkRenderer.make config=$(DarkRenderer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f DarkRenderer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  fpga"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DarkRenderer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"